name: Python_pipeline

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version Java
        uses: actions/setup-java@v2
        with:
          python-version: '3.12.2'

      - name: Check style project
        run: |
          pip install pycodestyle
          pycodestyle .