name: Python_pipeline

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11


      - name: Check style project
        run: |
          java -jar checkstyle-10.15.0-all.jar
          -c /sun_checks.xml adminController.java