name: Java_pipeline

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11


      - name: Check style project
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar
          java -jar checkstyle-8.44-all.jar -c path/to/checkstyle.xml .